---
repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.14.0
      hooks:
          - id: ruff
            additional_dependencies: [black, flake8, isort, pylint]

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.8.0
      hooks:
          - id: mypy

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-yaml
          - id: pretty-format-json
            args: ["--autofix"]
          - id: end-of-file-fixer

    - repo: https://github.com/PyCQA/bandit
      rev: 1.8.6
      hooks:
          - id: bandit
            args: ["--recursive", "--exclude", "tests"]

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.37.1
      hooks:
          - id: yamllint
