---
version: 1
disable_existing_loggers: false

formatters:
    detailed:
        format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

    json:
        class: pythonjsonlogger.jsonlogger.JsonFormatter
        format: "%(asctime)s %(name)s %(levelname)s %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: detailed
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: json
        filename: app.log
        maxBytes: 10485760
        backupCount: 5

loggers:
    src.domain:
        level: DEBUG
        handlers: [console, file]
        propagate: true

    src.application:
        level: DEBUG
        handlers: [console, file]
        propagate: true

    src.adapters:
        level: DEBUG
        handlers: [console, file]
        propagate: true

    # FastAPI logging overwrite
    uvicorn:
        level: INFO
        handlers: [console, file]
        propagate: false

    uvicorn.access:
        level: INFO
        handlers: [console, file]
        propagate: false

    uvicorn.error:
        level: INFO
        handlers: [console, file]
        propagate: false

    fastapi:
        level: INFO
        handlers: [console, file]
        propagate: false

    # SQLAlchemy
    sqlalchemy.engine:
        level: WARNING
        handlers: [console]
        propagate: false

root:
    level: INFO
    handlers: [console, file]
