"""Add initial tables

Revision ID: a4d468b4e4f2
Revises:
Create Date: 2025-10-16 11:15:57.656295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4d468b4e4f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bond",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nominal_value", sa.Numeric(), nullable=False),
        sa.Column("series", sa.String(), nullable=False),
        sa.Column("maturity_period", sa.Integer(), nullable=False),
        sa.Column("initial_interest_rate", sa.Numeric(), nullable=False),
        sa.Column("first_interest_period", sa.Integer(), nullable=False),
        sa.Column("reference_rate_margin", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bond")),
    )
    op.create_index(op.f("ix_bond_series"), "bond", ["series"], unique=True)
    op.create_table(
        "referencerate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referencerate")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_table(
        "bondholder",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("bond_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bond_id"], ["bond.id"], name=op.f("fk_bondholder_bond_id_bond")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_bondholder_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bondholder")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bondholder")
    op.drop_table("user")
    op.drop_table("referencerate")
    op.drop_index(op.f("ix_bond_series"), table_name="bond")
    op.drop_table("bond")
    # ### end Alembic commands ###
