FROM python:3.13-slim

ARG PROJECT_DIR=/home/app
WORKDIR $PROJECT_DIR

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml alembic.ini uv.lock ./

RUN uv sync --frozen && rm -rf /root/.cache/pip

ENV PATH="/home/app/.venv/bin:$PATH"

COPY src ./src

CMD ["uv", "run", "alembic", "upgrade", "head"]