FROM python:3.13-slim
ARG PROJECT_DIR=/home/app

WORKDIR $PROJECT_DIR

COPY ../pyproject.toml README.md alembic.ini uv.lock $PROJECT_DIR/
COPY ../src/adapters $PROJECT_DIR/src/adapters/
COPY ../src/__init__.py $PROJECT_DIR/src

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
RUN uv sync --frozen
